name: Migrate images

on:
  push:
    branches:
    - main

jobs:
  migrate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Migrate images
        run: |
          pwd
          ls -lh ${pwd}
          docker run -u root -t --rm -v ${pwd}:/migrate -v --entrypoint /bin/sh alpine:3.20 -c 'apk update && apk add skopeo && skopeo -v && skopeo login -u "${{ secrets.ALI_REGISTRY_USERNAME }}" -p "${{ secrets.ALI_REGISTRY_PASSWORD }}" registry.cn-beijing.aliyuncs.com && ls -lh /migrate && chmod -R 777 /migrate && ls -lh /migrate  && /migrate/migrate.sh'
