name: Migrate images

on:
  push:
    branches:
    - main

jobs:
  migrate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Migrate images
        run: |
          docker login -u "${{ secrets.ALI_REGISTRY_USERNAME }}" -p "${{ secrets.ALI_REGISTRY_PASSWORD }}" registry.cn-beijing.aliyuncs.com
          chmod +x ./migrate.sh
          ./migrate.sh
