name: Migrate images

on:
  push:
    branches:
    - main

jobs:
  migrate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Migrate images
        run: |
          docker run -u root -t --rm -v $(pwd)/migrate.sh:/tmp/migrate.sh -v $(pwd)/images.txt:/tmp/images.txt -v --entrypoint /bin/sh alpine:3.20 -c 'apk update && apk add skopeo && skopeo -v && skopeo login -u "${{ secrets.ALI_REGISTRY_USERNAME }}" -p "${{ secrets.ALI_REGISTRY_PASSWORD }}" registry.cn-beijing.aliyuncs.com && ls -lh /tmp && chmod 777 /tmp/migrate.sh && ls -lh /tmp  && /tmp/migrate.sh'
