name: Migrate images

on:
  push:
    branches:
    - main

jobs:
  migrate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Migrate images
        run: |
          docker run -u root -t --rm \
            -v $(pwd)/migrate-images.sh:/tmp/migrate-images.sh \
            -v $(pwd)/images.txt:/tmp/images.txt \
            --entrypoint /bin/sh \
            alpine:3.20 -c \
              'apk update && apk add skopeo && skopeo -v && skopeo login -u "${{ secrets.ALI_REGISTRY_USERNAME }}" -p "${{ secrets.ALI_REGISTRY_PASSWORD }}" registry.cn-beijing.aliyuncs.com && chmod 777 /tmp/migrate-images.sh && /tmp/migrate-images.sh'
          bash ./migrate-files.sh "${{ secrets.OSS_ACCESS_KEY_ID }}" "${{ secrets.OSS_ACCESS_KEY }}"
